/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author guilherme.vcmoz
 */
public class Ajuda extends javax.swing.JFrame {

    /**
     * Creates new form Ajuda
     */
    public Ajuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btMenu = new javax.swing.JMenuItem();
        jFornecedores = new javax.swing.JMenu();
        btFornecedores = new javax.swing.JMenuItem();
        jEstoque = new javax.swing.JMenu();
        btEstoque2 = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        btAjuda2 = new javax.swing.JMenuItem();
        jFeedback = new javax.swing.JMenu();
        btFeedback = new javax.swing.JMenuItem();
        QuemSomos2 = new javax.swing.JMenu();
        btQuemSomos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGTRAB.PNG"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Em caso de erros  ou duvidas entre em contato conosco:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whats.png"))); // NOI18N
        jLabel3.setText("(11) 94078-7889 / (11) 89003-7893");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-email-30.png"))); // NOI18N
        jLabel5.setText(" laartesequipe@gmail.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(179, 179, 179))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jMenu.add(btMenu);

        jMenuBar1.add(jMenu);

        jFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jFornecedores.setText("Fornecedores");

        btFornecedores.setText("Fornecedores");
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jFornecedores.add(btFornecedores);

        jMenuBar1.add(jFornecedores);

        jEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jEstoque.setText("Estoque");

        btEstoque2.setText("Estoque");
        btEstoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoque2ActionPerformed(evt);
            }
        });
        jEstoque.add(btEstoque2);

        jMenuBar1.add(jEstoque);

        jAjuda.setForeground(new java.awt.Color(255, 255, 255));
        jAjuda.setText("Ajuda");

        btAjuda2.setText("Ajuda");
        btAjuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjuda2ActionPerformed(evt);
            }
        });
        jAjuda.add(btAjuda2);

        jMenuBar1.add(jAjuda);

        jFeedback.setForeground(new java.awt.Color(255, 255, 255));
        jFeedback.setText("Feedback");

        btFeedback.setText("Feedback");
        jFeedback.add(btFeedback);

        jMenuBar1.add(jFeedback);

        QuemSomos2.setForeground(new java.awt.Color(255, 255, 255));
        QuemSomos2.setText("Quem Somos");

        btQuemSomos.setText("Quem Somos");
        QuemSomos2.add(btQuemSomos);

        jMenuBar1.add(QuemSomos2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        Principal uf = new Principal();
        uf.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    private void btEstoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoque2ActionPerformed
        // TODO add your handling code here:
        TelaEstoque uf = new TelaEstoque();
        uf.setVisible(true);
    }//GEN-LAST:event_btEstoque2ActionPerformed

    private void btAjuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjuda2ActionPerformed
        // TODO add your handling code here:
        Ajuda uf = new Ajuda();
        uf.setVisible(true);
    }//GEN-LAST:event_btAjuda2ActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        // TODO add your handling code here:
        Fornecedores uf = new Fornecedores();
        uf.setVisible(true);
    }//GEN-LAST:event_btFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QuemSomos2;
    private javax.swing.JMenuItem btAjuda2;
    private javax.swing.JMenuItem btEstoque2;
    private javax.swing.JMenuItem btFeedback;
    private javax.swing.JMenuItem btFornecedores;
    private javax.swing.JMenuItem btMenu;
    private javax.swing.JMenuItem btQuemSomos;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JMenu jFeedback;
    private javax.swing.JMenu jFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
