/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author adm
 */
public class QuemSomos extends javax.swing.JFrame {

    /**
     * Creates new form QuemSomos
     */
    public QuemSomos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btMenu = new javax.swing.JMenuItem();
        jEstoque = new javax.swing.JMenu();
        btEstoque2 = new javax.swing.JMenuItem();
        jFornecedores = new javax.swing.JMenu();
        btFornecedores2 = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        btAjuda2 = new javax.swing.JMenuItem();
        jAjuda1 = new javax.swing.JMenu();
        btQuemsomos3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGTRAB.PNG"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Muito prazer somos a La' Artes, um empresa especializada em sistemas de estoques,\nonde disponibizamos esse software para empresas que estejam querendo chegar a \nsua máxima produtividade,  fornecendo uma ótima experiência a seu cliente final.");
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu.setBackground(new java.awt.Color(0, 0, 0));
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jMenu.add(btMenu);

        jMenuBar1.add(jMenu);

        jEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jEstoque.setText("Estoque");

        btEstoque2.setText("Estoque");
        btEstoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoque2ActionPerformed(evt);
            }
        });
        jEstoque.add(btEstoque2);

        jMenuBar1.add(jEstoque);

        jFornecedores.setBackground(new java.awt.Color(0, 0, 0));
        jFornecedores.setBorder(null);
        jFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jFornecedores.setText("Fornecedores");

        btFornecedores2.setText("Fornecedores");
        btFornecedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedores2ActionPerformed(evt);
            }
        });
        jFornecedores.add(btFornecedores2);

        jMenuBar1.add(jFornecedores);

        jAjuda.setBorder(null);
        jAjuda.setForeground(new java.awt.Color(255, 255, 255));
        jAjuda.setText("Ajuda");

        btAjuda2.setText("Ajuda");
        btAjuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjuda2ActionPerformed(evt);
            }
        });
        jAjuda.add(btAjuda2);

        jMenuBar1.add(jAjuda);

        jAjuda1.setBackground(new java.awt.Color(0, 0, 0));
        jAjuda1.setBorder(null);
        jAjuda1.setForeground(new java.awt.Color(255, 255, 255));
        jAjuda1.setText("Quem Somos");

        btQuemsomos3.setText("Quem somos");
        btQuemsomos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuemsomos3ActionPerformed(evt);
            }
        });
        jAjuda1.add(btQuemsomos3);

        jMenuBar1.add(jAjuda1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        Principal uf = new Principal();
        uf.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    private void btEstoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoque2ActionPerformed
        // TODO add your handling code here:
        TelaEstoque uf = new TelaEstoque();
        uf.setVisible(true);
    }//GEN-LAST:event_btEstoque2ActionPerformed

    private void btFornecedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedores2ActionPerformed
        // TODO add your handling code here:
        Fornecedores uf = new Fornecedores();
        uf.setVisible(true);
    }//GEN-LAST:event_btFornecedores2ActionPerformed

    private void btAjuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjuda2ActionPerformed
        // TODO add your handling code here:
        Ajuda uf = new Ajuda();
        uf.setVisible(true);
    }//GEN-LAST:event_btAjuda2ActionPerformed

    private void btQuemsomos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuemsomos3ActionPerformed
        // TODO add your handling code here:
        QuemSomos uf = new QuemSomos();
        uf.setVisible(true);
    }//GEN-LAST:event_btQuemsomos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuemSomos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAjuda2;
    private javax.swing.JMenuItem btEstoque2;
    private javax.swing.JMenuItem btFornecedores2;
    private javax.swing.JMenuItem btMenu;
    private javax.swing.JMenuItem btQuemsomos3;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jAjuda1;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JMenu jFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
