/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme.vcmoz
 */
public class TelaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        btInserir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtArtista = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btMenu = new javax.swing.JMenuItem();
        jEstoque = new javax.swing.JMenu();
        btEstoque2 = new javax.swing.JMenuItem();
        jFornecedores = new javax.swing.JMenu();
        btFornecedores = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        btAjuda2 = new javax.swing.JMenuItem();
        jFeedback = new javax.swing.JMenu();
        btFeedback = new javax.swing.JMenuItem();
        QuemSomos2 = new javax.swing.JMenu();
        btQuemSomos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estoque");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Categoria:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 26, 85, -1));

        jLabel2.setText("Produto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 29, -1, -1));

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 26, 86, -1));

        jLabel3.setText("Quantidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 29, -1, -1));

        txtQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 26, 54, -1));

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 66, -1, -1));

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 66, -1, -1));

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 66, -1, -1));

        jLabel4.setText("Artista:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 29, -1, -1));

        txtArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 26, 94, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Produto", "Quantidade", "Artista"
            }
        ));
        jScrollPane1.setViewportView(tbProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 390));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu.setBackground(new java.awt.Color(0, 0, 0));
        jMenu.setBorder(null);
        jMenu.setForeground(new java.awt.Color(255, 255, 255));
        jMenu.setText("Menu");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jMenu.add(btMenu);

        jMenuBar1.add(jMenu);

        jEstoque.setBackground(new java.awt.Color(0, 0, 0));
        jEstoque.setBorder(null);
        jEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jEstoque.setText("Estoque");

        btEstoque2.setText("Estoque");
        btEstoque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstoque2ActionPerformed(evt);
            }
        });
        jEstoque.add(btEstoque2);

        jMenuBar1.add(jEstoque);

        jFornecedores.setBackground(new java.awt.Color(0, 0, 0));
        jFornecedores.setBorder(null);
        jFornecedores.setForeground(new java.awt.Color(255, 255, 255));
        jFornecedores.setText("Fornecedores");

        btFornecedores.setText("Fornecedores");
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jFornecedores.add(btFornecedores);

        jMenuBar1.add(jFornecedores);

        jAjuda.setBackground(new java.awt.Color(0, 0, 0));
        jAjuda.setBorder(null);
        jAjuda.setForeground(new java.awt.Color(255, 255, 255));
        jAjuda.setText("Ajuda");

        btAjuda2.setText("Ajuda");
        btAjuda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjuda2ActionPerformed(evt);
            }
        });
        jAjuda.add(btAjuda2);

        jMenuBar1.add(jAjuda);

        jFeedback.setBackground(new java.awt.Color(0, 0, 0));
        jFeedback.setBorder(null);
        jFeedback.setForeground(new java.awt.Color(255, 255, 255));
        jFeedback.setText("Feedback");

        btFeedback.setText("Feedback");
        btFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFeedbackActionPerformed(evt);
            }
        });
        jFeedback.add(btFeedback);

        jMenuBar1.add(jFeedback);

        QuemSomos2.setBackground(new java.awt.Color(0, 0, 0));
        QuemSomos2.setBorder(null);
        QuemSomos2.setForeground(new java.awt.Color(255, 255, 255));
        QuemSomos2.setText("Quem Somos");

        btQuemSomos.setText("Quem Somos");
        btQuemSomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuemSomosActionPerformed(evt);
            }
        });
        QuemSomos2.add(btQuemSomos);

        jMenuBar1.add(QuemSomos2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Produtos = (DefaultTableModel) tbProdutos.getModel();
        Object[] dados = {txtCodigo.getText(), txtProduto.getText(), txtQtde.getText(), txtArtista.getText()};
        Produtos.addRow(dados);
    }//GEN-LAST:event_btInserirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if(tbProdutos.getSelectedRow() != -1) {
            tbProdutos.setValueAt(txtCodigo.getText(), tbProdutos.getSelectedRow(), 0);
            tbProdutos.setValueAt(txtProduto.getText(), tbProdutos.getSelectedRow(), 1);
            tbProdutos.setValueAt(txtQtde.getText(), tbProdutos.getSelectedRow(), 2);
            tbProdutos.setValueAt(txtArtista.getText(), tbProdutos.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if(tbProdutos.getSelectedRow() != -1) {
            DefaultTableModel Produtos = (DefaultTableModel) tbProdutos.getModel();
            Produtos.removeRow(tbProdutos.getSelectedRow());
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        Principal uf = new Principal();
        uf.setVisible(true);
    }//GEN-LAST:event_btMenuActionPerformed

    private void btEstoque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstoque2ActionPerformed
        // TODO add your handling code here:
        TelaEstoque uf = new TelaEstoque();
        uf.setVisible(true);
    }//GEN-LAST:event_btEstoque2ActionPerformed

    private void txtArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaActionPerformed

    private void txtQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdeActionPerformed

    private void btQuemSomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuemSomosActionPerformed
        // TODO add your handling code here:
        QuemSomos uf = new QuemSomos();
        uf.setVisible(true);  
    }//GEN-LAST:event_btQuemSomosActionPerformed

    private void btAjuda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjuda2ActionPerformed
        // TODO add your handling code here:
        Ajuda uf = new Ajuda();
        uf.setVisible(true);
    }//GEN-LAST:event_btAjuda2ActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        // TODO add your handling code here:
        Fornecedores uf = new Fornecedores();
        uf.setVisible(true);
    }//GEN-LAST:event_btFornecedoresActionPerformed

    private void btFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFeedbackActionPerformed
        // TODO add your handling code here:
        Feedback uf = new Feedback();
        uf.setVisible(true);
    }//GEN-LAST:event_btFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QuemSomos2;
    private javax.swing.JMenuItem btAjuda2;
    private javax.swing.JButton btAlterar;
    private javax.swing.JMenuItem btEstoque2;
    private javax.swing.JButton btExcluir;
    private javax.swing.JMenuItem btFeedback;
    private javax.swing.JMenuItem btFornecedores;
    private javax.swing.JButton btInserir;
    private javax.swing.JMenuItem btMenu;
    private javax.swing.JMenuItem btQuemSomos;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jEstoque;
    private javax.swing.JMenu jFeedback;
    private javax.swing.JMenu jFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtde;
    // End of variables declaration//GEN-END:variables
}
